# Task 10: Introduction to NumPy (arrays, basic operations)

## Numpy Practice

### importing numpy library

In [1]:
import numpy as np   # we can also write any word of our choice instead of 'np' but 'np' is most commonly used as a standard.

## 1D Array

### 1D array using np.arange

In [2]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1D array using np.array

In [3]:
a2=np.array([1,2,3,4,5,6,7,8,9])
print(a2)

[1 2 3 4 5 6 7 8 9]


In [4]:
type(a2)

numpy.ndarray

### 1D array using np.zeros containing zeros

In [5]:
a4=np.zeros(5)
print(a4)

[0. 0. 0. 0. 0.]


### 1D array using np.ones containing ones

In [6]:
a5=np.ones(10)
print(a5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 1D array using np.random.randint containing random numbers with size and range(min,max) of array specified

In [7]:
a6=np.random.randint(1,10,size=7)
print(a6)

[4 2 1 4 1 9 6]


### 1D array using np.random.rand containing random floats in the range [0, 1) with size of array specified

In [8]:
a7=np.random.rand(7)
print(a7)

[0.4208696  0.71640041 0.18554908 0.21690456 0.15057108 0.7953701
 0.19185985]


### 1D array using np.linspace

In [9]:
a8=np.linspace(0,1,5)  # Creates an array with 5 equally spaced values from 0 to 1
print(a8)

[0.   0.25 0.5  0.75 1.  ]


### Sum of 1D arrays

In [10]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
sum = np.add(array1, array2)
print(sum)

[ 7  9 11 13 15]


### Product of 1D arrays

In [11]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
prod = np.multiply(array1, array2)
print(prod)

[ 6 14 24 36 50]


### Dot Product of 1D arrays

In [12]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
dot_prod = np.dot(array1, array2)
print(dot_prod)

130


### Mean, Median, Mode of 1D arrays

In [13]:
array3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Mean=",np.mean(array3))
print("\nMedian=",np.median(array3))
print("\nMode=",np.std(array3))

Mean= 5.5

Median= 5.5

Mode= 2.8722813232690143


### Min, Max, Cumulative Sum of 1D arrays, Uniform Distribution, Correlation Coefficient Matrix

In [14]:
array4 = np.random.randint(1, 100, size=5)
print(array4)
print("Min=",np.min(array4))
print("\nMax=",np.max(array4))
#uniform_distribution_array = np.random.randint(10, 51, size=(5, 5))
#print("\nCreate a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50 =\n",np.max(array4))
print("\nCumulative Sum =",np.cumsum(array4))
print("\nUniform Distribution=",np.max(array4))
print("\nCorrelation Coefficient Matrix=",np.corrcoef(array4))

[70 17  7 17 73]
Min= 7

Max= 73

Cumulative Sum = [ 70  87  94 111 184]

Uniform Distribution= 73

Correlation Coefficient Matrix= 1.0


### Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1

In [15]:
normal_distribution = np.random.normal(0, 1, 1000)
print(normal_distribution)

[-1.62713373e+00 -1.52378882e+00 -1.02933449e-01  1.49407254e+00
  1.10219842e+00 -5.23520112e-01  4.59531887e-01 -1.36938129e+00
 -1.00017659e+00  4.86867496e-01 -8.83699757e-03  3.28685945e-01
 -3.75141112e-01 -2.19823099e-01 -8.87367526e-01 -1.68160491e+00
  1.32686982e-01 -6.99965072e-01  1.04726723e+00 -4.03622186e-01
  8.09901978e-01 -5.51581732e-02  9.89711055e-01 -1.28852949e-01
 -5.21341257e-01  1.38599922e+00  4.08213584e-01  4.20856638e-01
 -1.28048151e+00  9.05698226e-01  4.45862383e-01  1.97519023e-01
 -3.74421727e-01 -6.57377142e-01 -2.49085140e-01  2.09392449e+00
  4.90648809e-01 -1.92113011e+00 -4.58498190e-01 -1.31559107e+00
  6.54276136e-01  1.78931257e+00 -1.14541240e+00 -7.17744075e-01
 -9.77650608e-01 -7.67615853e-02 -2.80901649e-01  8.43876458e-01
  5.91254909e-01  2.87731780e-01 -3.65872177e-01 -5.58126280e-02
 -1.56466073e-01 -2.53368636e-01  9.88337423e-01  1.59340978e+00
 -1.68422395e+00  1.37199422e-01 -1.79051568e+00  1.32841789e+00
  2.47220538e-01  4.86738

## 2D arrays

### 2D array using np.array

In [16]:
a9=np.array([ [ [1,2],
                [3,4] ],
             
              [ [5,6],
                [7,8] ] ])
print(a9)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 2D array using npa.zeros containing zeros

In [17]:
a10 =np.zeros((3,3))
print(a10)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 2D array using np.ones containing ones

In [18]:
a11 =np.ones((3,3))
print(a11)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 2D array using np.random.randint containing random numbers with size and range(min,max) of array specified

In [19]:
a12 =np.random.randint(1,10,size=(3,3))
print(a12)

[[7 7 3]
 [2 9 7]
 [1 8 9]]


### 2D array using np.random.rand containing random numbers with size of array

In [20]:
a13 =np.random.rand(3,3)
print(a13)

[[0.24614102 0.70218421 0.01515273]
 [0.25167773 0.48983308 0.6113735 ]
 [0.03486659 0.42505601 0.56766276]]


### 2D array using np.eye creating identity matrix

In [21]:
a14 =np.eye(3)
print(a14)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2D array using np.full /fill 2D array with specified number

In [22]:
a15 =np.full((3,3),7)
print(a15)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Sum, Product, Dot Product of 2D arrays

In [23]:
array1 = np.array([[[1,2],
                    [3,4]],
             
                  [[5,6],
                    [7,8]]])
array2 = np.array([[[4,2],
                    [11,9]],
             
                  [[11,20],
                    [100,50]]])
sum = np.add(array1, array2)
print("\nSum:",sum)
prod = np.multiply(array1, array2)
print("\nProduct=",prod)
dot_prod = np.dot(array1, array2)
print("\nDot Product=",dot_prod)


Sum: [[[  5   4]
  [ 14  13]]

 [[ 16  26]
  [107  58]]]

Product= [[[  4   4]
  [ 33  36]]

 [[ 55 120]
  [700 400]]]

Dot Product= [[[[ 26  20]
   [211 120]]

  [[ 56  42]
   [433 260]]]


 [[[ 86  64]
   [655 400]]

  [[116  86]
   [877 540]]]]


### Mean, Median, Mode of 2D arrays

In [24]:
array3 = np.random.randint(1,10,size=(3,3))
print("Mean=",np.mean(array3))
print("\nMedian=",np.median(array3))
print("\nMode=",np.std(array3))

Mean= 4.0

Median= 2.0

Mode= 2.9059326290271157


### Min, Max, Cumulative Sum of 2D arrays, Uniform Distribution, Correlation Coefficient Matrix

In [25]:
array4 = np.random.randint(1, 100, size=(4, 5))
print(array4)
print("Min=",np.min(array4))
print("\nMax=",np.max(array4))
uniform_distribution_array = np.random.randint(10, 51, size=(5, 5))
print("\nCreate a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50 =\n",uniform_distribution_array)
print("\nCumulative Sum =",np.cumsum(array4))
print("\nUniform Distribution=",np.max(array4))
print("\nCorrelation Coefficient Matrix=",np.corrcoef(array4))

[[39 87 34 76 58]
 [52 37 47 35 23]
 [99 89 43 53 36]
 [91 55  4 72 75]]
Min= 4

Max= 99

Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50 =
 [[23 30 31 45 41]
 [48 24 39 39 47]
 [25 37 28 27 11]
 [44 42 45 39 30]
 [17 19 46 46 31]]

Cumulative Sum = [  39  126  160  236  294  346  383  430  465  488  587  676  719  772
  808  899  954  958 1030 1105]

Uniform Distribution= 99

Correlation Coefficient Matrix= [[ 1.         -0.54984737  0.14131627  0.26987962]
 [-0.54984737  1.          0.57167683 -0.21411667]
 [ 0.14131627  0.57167683  1.          0.41818391]
 [ 0.26987962 -0.21411667  0.41818391  1.        ]]


## 3D arrays

### 3D array using np.array

In [26]:
a16 = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
print(a16)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 3D array using npa.zeros containing zeros

In [27]:
a17 = np.zeros((2, 3, 4)) 
print(a17)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 3D array using np.ones containing ones

In [28]:
a18 = np.ones((2, 3, 4)) 
print(a18)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 3D array using np.random.randint containing random numbers with size and range(min,max) of array specified

In [29]:
a19 = np.random.randint(1,20,size=(2, 3, 4)) 
print(a19)

[[[ 6 18  1 13]
  [ 8 14  1 12]
  [ 5 11 12  6]]

 [[18  5  6 17]
  [11 16  7  5]
  [13  8  3  6]]]


### 3D array using np.random.rand containing random numbers with size of array

In [30]:
a20 = np.random.rand(3,3,3) 
print(a20)

[[[0.44938691 0.28464837 0.46434043]
  [0.65290531 0.38561697 0.84024877]
  [0.63278806 0.09780028 0.30947231]]

 [[0.87959996 0.4650577  0.65844521]
  [0.76399458 0.57211052 0.34969048]
  [0.30195279 0.16779725 0.80999858]]

 [[0.75327496 0.26627224 0.79834525]
  [0.95620304 0.40256542 0.41603552]
  [0.09013316 0.74701573 0.06666058]]]


### 3D array using np.full 

In [31]:
a21= np.full((2,3,4),7) 
print(a21)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


### 3D array using np.arange and reshape 

In [32]:
a22 = np.arange(24).reshape((2, 3, 4))  # Creates a 2x3x4 array with values from 0 to 23
print(a22)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Sum, Product, Dot Product of 3D arrays

In [33]:
array1 = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
array2 = np.array([[[10, 20, 30], [40, 50, 60]],
                [[70, 80, 90], [100, 110, 120]]])
sum = np.add(array1, array2)
print("\nSum:",sum)
prod = np.multiply(array1, array2)
print("\nProduct=",prod)

array3=array1.reshape(3,2,2)
array4=array2.reshape(3,2,2)
dot_prod = np.dot(array3, array3)
print("\nDot Product=",dot_prod)


Sum: [[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [110 121 132]]]

Product= [[[  10   40   90]
  [ 160  250  360]]

 [[ 490  640  810]
  [1000 1210 1440]]]

Dot Product= [[[[  7  10]
   [ 19  22]
   [ 31  34]]

  [[ 15  22]
   [ 43  50]
   [ 71  78]]]


 [[[ 23  34]
   [ 67  78]
   [111 122]]

  [[ 31  46]
   [ 91 106]
   [151 166]]]


 [[[ 39  58]
   [115 134]
   [191 210]]

  [[ 47  70]
   [139 162]
   [231 254]]]]


### Mean, Median, Mode of 3D arrays

In [34]:
array3 = np.random.randint(1,10,size=(3,3,3))
print("Mean=",np.mean(array3))
print("\nMedian=",np.median(array3))
print("\nMode=",np.std(array3))

Mean= 4.962962962962963

Median= 5.0

Mode= 2.3645762517796105


### Min, Max, Cumulative Sum of 3D arrays, Uniform Distribution

In [35]:
array4 = np.random.randint(1, 100, size=(2, 3, 4))
print(array4)
print("Min=",np.min(array4))
print("\nMax=",np.max(array4))
uniform_distribution_array = np.random.randint(10, 51, size=(5, 5, 5))
print("\nCreate a 3D array of shapes (5, 5, 5) with random integers from a uniform distribution between 10 and 50 =\n",uniform_distribution_array)
print("\nCumulative Sum =",np.cumsum(array4))
print("\nUniform Distribution=",np.max(array4))

[[[ 3 73 18 41]
  [47 14 17 52]
  [ 3 83 49 24]]

 [[50 76 92 63]
  [72 35 69 22]
  [21 34 64 69]]]
Min= 3

Max= 92

Create a 3D array of shapes (5, 5, 5) with random integers from a uniform distribution between 10 and 50 =
 [[[37 32 22 48 18]
  [21 27 14 11 45]
  [32 15 28 45 14]
  [31 25 26 15 40]
  [19 48 12 41 12]]

 [[14 39 28 42 23]
  [12 16 25 33 28]
  [22 23 18 35 20]
  [47 39 36 13 35]
  [19 31 30 20 38]]

 [[31 45 50 33 29]
  [48 35 42 24 27]
  [23 44 22 21 15]
  [42 22 28 43 28]
  [48 35 41 46 13]]

 [[31 18 20 10 39]
  [28 30 41 24 13]
  [35 32 31 20 19]
  [32 40 42 15 35]
  [30 17 23 37 48]]

 [[14 10 16 31 46]
  [15 41 45 46 10]
  [32 23 20 20 31]
  [46 41 28 10 20]
  [20 26 21 18 27]]]

Cumulative Sum = [   3   76   94  135  182  196  213  265  268  351  400  424  474  550
  642  705  777  812  881  903  924  958 1022 1091]

Uniform Distribution= 92


## Some Problems of Task 09

### Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.

In [36]:
die_rolls = np.random.randint(1, 7, size=1000)
die_rolls_frequency = np.bincount(die_rolls)[1:]  # bincount includes zero count
print(die_rolls_frequency)

[142 164 171 176 180 167]


### Find the mean of the following set of numbers: 2, 4, 6, 8, 10.

In [37]:
numbers = np.array([2, 4, 6, 8, 10])
mean_numbers = np.mean(numbers)
print(mean_numbers)

6.0


### The daily temperatures for a week are recorded as 20°C, 22°C, 19°C, 24°C, 21°C, 23°C, and 20°C. Calculate the mean temperature

In [38]:
temperatures = np.array([20, 22, 19, 24, 21, 23, 20])
mean_temperature = np.mean(temperatures)
print(mean_temperature)

21.285714285714285


### Find the median of the set: 3, 1, 4, 1, 5, 9.

In [39]:
set1 = np.array([3, 1, 4, 1, 5, 9])
median_set1 = np.median(set1)
print(median_set1)

3.5


### Determine the median of these numbers: 45, 67, 23, 89, 12, 54, 33, 72.

In [40]:
set2 = np.array([45, 67, 23, 89, 12, 54, 33, 72])
median_set2 = np.median(set2)
print(median_set2)

49.5


### Identify the mode in the dataset: 5, 3, 9, 3, 2, 3, 4, 6, 5.

In [41]:
mode_set1 = np.std([5, 3, 9, 3, 2, 3, 4, 6, 5])
print(mode_set1)

2.006163342807532


### Find the mode of the following test scores: 56, 72, 89, 56, 94, 56, 78, 72.

In [42]:
mode_set2 = np.std([56, 72, 89, 56, 94, 56, 78, 72])
print(mode_set2)

14.03511221900274


### Given a normal distribution with a mean of 50 and a standard deviation of 5, find the probability that a value is between 45 and 55.

In [43]:
from scipy import special,stats # used form finding norm and combination and other mathematical function
mean = 50
std_dev = 5
prob_between_45_55 = stats.norm.cdf(55, mean, std_dev) - stats.norm.cdf(45, mean, std_dev)
print(prob_between_45_55)

0.6826894921370859


### Calculate the z-score for a value of 60 in a normal distribution with a mean of 50 and a standard deviation of 10.

In [44]:
value = 60
mean = 50
std_dev = 10
z_score = (value - mean) / std_dev
print(z_score)

1.0


### If a coin is flipped 10 times, what is the probability of getting exactly 6 heads?

In [45]:
n = 10
k = 6
p = 0.5
prob_6_heads = special.comb(n, k) * (p ** k) * ((1 - p) ** (n - k))
print(prob_6_heads)

0.205078125


### In a survey, 60% of people prefer chocolate ice cream. What is the probability that out of 8 randomly selected people, exactly 5 prefer chocolate ice cream?

In [46]:
p_chocolate = 0.6
n_people = 8
k_chocolate = 5
prob_5_chocolate = special.comb(n_people, k_chocolate) * (p_chocolate ** k_chocolate) * ((1 - p_chocolate) ** (n_people - k_chocolate))
print(prob_5_chocolate)

0.27869184


### A call center receives an average of 5 calls per hour. What is the probability of receiving exactly 3 calls in an hour?

In [47]:
lambda_calls = 5
k_calls = 3
prob_3_calls = (lambda_calls ** k_calls * np.exp(-lambda_calls)) / special.factorial(k_calls)
print(prob_3_calls)

0.14037389581428056


### If a book has an average of 2 misprints per page, what is the probability that a page has no misprints?

In [48]:
lambda_misprints = 2
k_misprints = 0
prob_no_misprints = (lambda_misprints ** k_misprints * np.exp(-lambda_misprints)) / special.factorial(k_misprints)
print(prob_no_misprints)

0.1353352832366127
