# Task 21-> Linear algebra and calculus in NumPy
# Linear Algebra Tasks

In [1]:
import numpy as np

## Matrix Creation and Manipulation

### Zero Matrix: A matrix where all elements are zero.

In [2]:
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Identity Matrix: A square matrix with ones on the diagonal and zeros elsewhere.

In [3]:
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Random Matrix: A matrix with random elements.

In [4]:
random_matrix = np.random.rand(3, 3)
print("Random Matrix:\n", random_matrix)

Random Matrix:
 [[0.98522297 0.76381071 0.71943211]
 [0.27073441 0.36270211 0.09003325]
 [0.16279314 0.74871057 0.48954089]]


### Practice Problems:

#### Create a 4x4 zero matrix.

In [5]:
zero_matrix_4x4 = np.zeros((4, 4))
print(zero_matrix_4x4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Create a 5x5 identity matrix.

In [6]:
identity_matrix_5x5 = np.eye(5)
print(identity_matrix_5x5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Generate a 3x3 matrix with random integers between 0 and 10.

In [7]:
random_matrix_3x3 = np.random.randint(0, 11, (3, 3))
print(random_matrix_3x3)


[[1 7 8]
 [1 1 5]
 [3 2 4]]


### Create a 2x3 zero matrix.

In [8]:
zero_matrix_2x3 = np.zeros((2, 3))
print(zero_matrix_2x3)

[[0. 0. 0.]
 [0. 0. 0.]]


#### Generate a 6x6 matrix with random values between 0 and 1.

In [9]:
random_matrix_6x6 = np.random.rand(6, 6)
print(random_matrix_6x6)

[[0.30098176 0.27728786 0.59707207 0.35849931 0.53400981 0.38099542]
 [0.7568733  0.24394874 0.85368922 0.05491599 0.67054743 0.68571539]
 [0.51519248 0.89511588 0.42961534 0.7884417  0.71469828 0.43565083]
 [0.03335184 0.53594105 0.14522036 0.2176454  0.15403015 0.13577776]
 [0.96041264 0.58899153 0.04627009 0.534331   0.3771161  0.72485908]
 [0.1020893  0.42702527 0.62112021 0.26232405 0.75809525 0.95896584]]


## Basic Matrix Operations

### Addition of Matrices

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

addition = A + B
print("Addition:\n", addition)

Addition:
 [[ 6  8]
 [10 12]]


### Subtraction of Matrices

In [11]:
subtraction = A - B
print("Subtraction:\n", subtraction)

Subtraction:
 [[-4 -4]
 [-4 -4]]


### Multiplication (element-wise) of Matrices

In [12]:
multiplication_elementwise = A * B
print("Element-wise Multiplication:\n", multiplication_elementwise)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


### Matrix Multiplication (dot product) of Matrices


In [13]:
multiplication_dot = np.dot(A, B)
print("Matrix Multiplication:\n", multiplication_dot)

Matrix Multiplication:
 [[19 22]
 [43 50]]


### Practice Problems:

#### Add two 3x3 matrices

In [14]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
addition_result = A + B
print(addition_result)

[[0.13034227 0.59734357 0.63957895]
 [0.17113983 1.04694551 1.31933975]
 [1.60074621 0.46487057 0.33859704]]


#### Subtract a 2x2 matrix from another 2x2 matrix.

In [15]:
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)
subtraction_result = A - B
print(subtraction_result)

[[-0.56081401 -0.13683887]
 [ 0.23234452  0.74149217]]


#### Perform element-wise multiplication of two 4x4 matrices.

In [16]:
A = np.random.rand(4, 4)
B = np.random.rand(4, 4)
elementwise_multiplication_result = A * B
print(elementwise_multiplication_result)

[[0.3710826  0.04605086 0.58705177 0.48183767]
 [0.00650152 0.45867164 0.30841286 0.23527287]
 [0.06998351 0.21701783 0.0563074  0.13777982]
 [0.17437087 0.57802952 0.02410639 0.10374231]]


#### Compute the dot product of two matrices: 2x3 and 3x2.

In [17]:
A = np.random.rand(2, 3)
B = np.random.rand(3, 2)
dot_product_result = np.dot(A, B)
print(dot_product_result)

[[1.38458983 1.50841838]
 [1.13991784 1.19268624]]


#### Multiply a 3x3 matrix by a 3x3 identity matrix.

In [18]:
A = np.random.rand(3, 3)
identity_matrix = np.eye(3)
multiplication_result = np.dot(A, identity_matrix)
print(multiplication_result)

[[0.34687205 0.21536484 0.10040841]
 [0.15303808 0.57069057 0.98640951]
 [0.068653   0.29050825 0.50705476]]


## Transpose, Determinant, and Inverse

### Transpose of Matrices

In [19]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

transpose = np.transpose(C)
print("Transpose:\n", transpose)

Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


### Determinant of Matrices

In [20]:
determinant = np.linalg.det(C)
print("Determinant:\n", determinant)

Determinant:
 -9.51619735392994e-16


### Inverse of Matrices


In [21]:
try:
    inverse = np.linalg.inv(C)
    print("Inverse:\n", inverse)
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")

Inverse:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


### Practice Problems:

#### Transpose a 3x3 matrix.

In [22]:
A = np.random.rand(3, 3)
transpose_result = np.transpose(A)
print(transpose_result)

[[0.32736508 0.11866095 0.03524555]
 [0.2143446  0.28864214 0.58951292]
 [0.83360887 0.47641757 0.69435352]]


#### Find the determinant of a 2x2 matrix.

In [23]:
A = np.array([[1, 2], [3, 4]])
determinant_result = np.linalg.det(A)
print(determinant_result)

-2.0000000000000004


#### Compute the inverse of a 3x3 invertible matrix.

In [24]:
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
inverse_result = np.linalg.inv(A)
print(inverse_result)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


#### Find the transpose of a 4x4 matrix.

In [25]:
A = np.random.rand(4, 4)
transpose_result = np.transpose(A)
print(transpose_result)

[[0.92833688 0.6030786  0.75202915 0.44163062]
 [0.96098257 0.04067485 0.53849177 0.51443744]
 [0.24828907 0.48426245 0.49246544 0.86539503]
 [0.92230451 0.71959399 0.75640081 0.86882727]]


#### Determine if a 3x3 matrix is invertible and, if so, find its inverse.

In [26]:
A = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]])
try:
    inverse_result = np.linalg.inv(A)
    print(inverse_result)
except np.linalg.LinAlgError:
    print("Matrix is singular and cannot be inverted.")

[[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]


## Solving Linear Equations

### Use NumPy to solve a system of linear equations:

In [27]:
# Example system: 2x + 3y = 5, 4x + 6y = 10
A = np.array([[2, 3], [4, 6]])
b = np.array([5, 10])

try:
    solution = np.linalg.solve(A, b)
    print("Solution:\n", solution)
except np.linalg.LinAlgError:
    print("The system does not have a unique solution.")

The system does not have a unique solution.


### Practice Problems:

#### Solve the system: x+y=2, x−y=0.

In [28]:
A = np.array([[1, 1], [1, -1]])
b = np.array([2, 0])
solution = np.linalg.solve(A, b)
print(solution)

[1. 1.]


#### Solve the system: 3x+4y=7, 2x−y=3.

In [29]:
A = np.array([[3, 4], [2, -1]])
b = np.array([7, 3])
solution = np.linalg.solve(A, b)
print(solution)

[1.72727273 0.45454545]


#### Solve the system: x−2y+z=1, 2x+y+z=3, 3x−y+2z=2.

In [30]:
A = np.array([[1, -2, 1], [2, 1, 1], [3, -1, 2]])
b = np.array([1, 3, 2])
solution = np.linalg.solve(A, b)
print(solution)

[-1.62129587e+16  5.40431955e+15  2.70215978e+16]


#### Solve the system: 2x+3y=1, 4x−y=6.

In [31]:
A = np.array([[2, 3], [4, -1]])
b = np.array([1, 6])
solution = np.linalg.solve(A, b)
print(solution)

[ 1.35714286 -0.57142857]


#### Solve the system: x+y+z=6, 2x−y+z=3, x+2y−z=2.

In [32]:
A = np.array([[1, 1, 1], [2, -1, 1], [1, 2, -1]])
b = np.array([6, 3, 2])
solution = np.linalg.solve(A, b)
print(solution)

[1. 2. 3.]


### Implement matrix factorization methods (LU decomposition, QR decomposition):
### 1. LU Decomposition

In [33]:
from scipy.linalg import lu, qr
D = np.array([[2, 1, 1], [4, -6, 0], [-2, 7, 2]])

P, L, U = lu(D)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

P:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
L:
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5  1.   1. ]]
U:
 [[ 4. -6.  0.]
 [ 0.  4.  1.]
 [ 0.  0.  1.]]


### 2. QR Decomposition


In [34]:
Q, R = qr(D)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [-8.16496581e-01  1.64776939e-16  5.77350269e-01]
 [ 4.08248290e-01  7.07106781e-01  5.77350269e-01]]
R:
 [[-4.89897949  7.34846923  0.40824829]
 [ 0.          5.65685425  2.12132034]
 [ 0.          0.          0.57735027]]


### Practice Problems:

#### Perform LU decomposition on a 2x2 matrix.

In [35]:
A = np.array([[4, 3], [6, 3]])
P, L, U = lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

P:
 [[0. 1.]
 [1. 0.]]
L:
 [[1.         0.        ]
 [0.66666667 1.        ]]
U:
 [[6. 3.]
 [0. 1.]]


#### Perform QR decomposition on a 3x3 matrix.

In [36]:
A = np.random.rand(3, 3)
Q, R = qr(A)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[-5.46607955e-01  4.43670361e-01  7.10194588e-01]
 [-8.37388306e-01 -2.88844151e-01 -4.64058058e-01]
 [-7.53253237e-04 -8.48366470e-01  5.29408883e-01]]
R:
 [[-0.33550795 -0.95439181 -0.68950641]
 [ 0.         -0.09654819 -0.55984529]
 [ 0.          0.          0.71582063]]


#### Verify the result of LU decomposition by reconstructing the original matrix.

In [37]:
A = np.array([[4, 3], [6, 3]])
P, L, U = lu(A)
reconstructed_A = np.dot(P, np.dot(L, U))
print(reconstructed_A)

[[4. 3.]
 [6. 3.]]


#### Verify the result of QR decomposition by reconstructing the original matrix.

In [38]:
A = np.random.rand(3, 3)
Q, R = qr(A)
reconstructed_A = np.dot(Q, R)
print(reconstructed_A)

[[0.71178125 0.11867374 0.34113682]
 [0.08255353 0.22268258 0.95755013]
 [0.94116198 0.2676143  0.10832707]]


#### Apply LU decomposition on a 4x4 matrix.

In [39]:
A = np.random.rand(4, 4)
P, L, U = lu(A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)

P:
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]
L:
 [[1.         0.         0.         0.        ]
 [0.83040914 1.         0.         0.        ]
 [0.23427281 0.07033877 1.         0.        ]
 [0.11893396 0.30338411 0.81082823 1.        ]]
U:
 [[ 0.84015235  0.64925577  0.53259767  0.17233097]
 [ 0.          0.27573333 -0.2500363   0.21195055]
 [ 0.          0.          0.35828492  0.66782396]
 [ 0.          0.          0.         -0.29533392]]


## Eigenvalues and Eigenvectors

### Calculate the eigenvalues and eigenvectors of a given matrix:

In [40]:
E = np.array([[4, -2], [1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(E)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


### Practice Problems:

#### Find the eigenvalues of a 2x2 matrix.

In [41]:
A = np.array([[2, 1], [1, 2]])
eigenvalues, _ = np.linalg.eig(A)
print(eigenvalues)

[3. 1.]


#### Find the eigenvectors of a 3x3 matrix.

In [42]:
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
_, eigenvectors = np.linalg.eig(A)
print(eigenvectors)

[[ 0.22578016 -0.75769839 -0.49927017]
 [ 0.52634845  0.63212771 -0.46674201]
 [-0.81974424 -0.16219652 -0.72998712]]


#### Verify eigenvalues and eigenvectors by reconstructing the original matrix.

In [43]:
A = np.array([[4, -2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
reconstructed_A = np.dot(eigenvectors, np.dot(np.diag(eigenvalues), np.linalg.inv(eigenvectors)))
print(reconstructed_A)

[[ 4. -2.]
 [ 1.  1.]]


#### Compute the eigenvalues of a symmetric matrix.

In [44]:
A = np.array([[2, 1], [1, 2]])
eigenvalues, _ = np.linalg.eig(A)
print(eigenvalues)

[3. 1.]


#### Compute the eigenvectors of a diagonal matrix.

In [45]:
A = np.diag([1, 2, 3])
_, eigenvectors = np.linalg.eig(A)
print(eigenvectors)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Vector Operations
### Perform basic vector operations (addition, dot product, cross product):

### 1. Addition

In [46]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
addition = v1 + v2
print("Addition:\n", addition)

Addition:
 [5 7 9]


### 2. Dot Product


In [47]:
dot_product = np.dot(v1, v2)
print("Dot Product:\n", dot_product)

Dot Product:
 32


### 3. Cross Product


In [48]:
cross_product = np.cross(v1, v2)
print("Cross Product:\n", cross_product)

Cross Product:
 [-3  6 -3]


### Practice Problems:

#### Add two 3D vectors.

In [49]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
addition_result = v1 + v2
print(addition_result)

[5 7 9]


#### Compute the dot product of two 4D vectors.

In [50]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([4, 3, 2, 1])
dot_product_result = np.dot(v1, v2)
print(dot_product_result)

20


#### Find the cross product of two 3D vectors.

In [51]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
cross_product_result = np.cross(v1, v2)
print(cross_product_result)

[-3  6 -3]


#### Compute the dot product of two 2D vectors.

In [52]:
v1 = np.array([1, 2])
v2 = np.array([3, 4])
dot_product_result = np.dot(v1, v2)
print(dot_product_result)

11


#### Add a zero vector to a 3D vector.

In [53]:
v1 = np.array([1, 2, 3])
zero_vector = np.zeros(3)
addition_result = v1 + zero_vector
print(addition_result)

[1. 2. 3.]


### Normalize a vector and compute vector norms:
### 1. Norm (magnitude)

In [54]:
v = np.array([3, 4, 5])
norm = np.linalg.norm(v)
print("Norm:\n", norm)

Norm:
 7.0710678118654755


### 2. Normalized vector


In [55]:
normalized_v = v / norm
print("Normalized Vector:\n", normalized_v)

Normalized Vector:
 [0.42426407 0.56568542 0.70710678]


### Practice Problems:

#### Compute the norm of a 2D vector.

In [56]:
v = np.array([3, 4])
norm_result = np.linalg.norm(v)
print(norm_result)

5.0


#### Normalize a 4D vector.

In [57]:
v = np.array([1, 2, 3, 4])
norm = np.linalg.norm(v)
normalized_v = v / norm
print(normalized_v)

[0.18257419 0.36514837 0.54772256 0.73029674]


#### Find the norm of a vector with negative components.

In [58]:
v = np.array([-3, -4])
norm_result = np.linalg.norm(v)
print(norm_result)

5.0


#### Normalize a zero vector and handle any errors.

In [59]:
v = np.zeros(3)
norm = np.linalg.norm(v)
normalized_v = v / norm if norm != 0 else np.zeros_like(v)
print(normalized_v)

[0. 0. 0.]


#### Compute the norm of a unit vector.

In [60]:
v = np.array([1/np.sqrt(3), 1/np.sqrt(3), 1/np.sqrt(3)])
norm_result = np.linalg.norm(v)
print(norm_result)

1.0


### Matrix Decomposition
### Understand and implement Principal Component Analysis (PCA) using SVD:

### 1. PCA using SVD


In [61]:
from sklearn.decomposition import PCA
data = np.random.rand(10, 3)  # Random 10x3 data matrix

pca = PCA(n_components=2)
pca.fit(data)
transformed_data = pca.transform(data)
print("Transformed Data:\n", transformed_data)

Transformed Data:
 [[ 0.16903988 -0.38660349]
 [ 0.23288686  0.07016475]
 [ 0.52227245  0.1015772 ]
 [-0.28854069 -0.29908826]
 [-0.33312492  0.01136668]
 [-0.05251928  0.48328433]
 [-0.51049669 -0.13602644]
 [ 0.58478517 -0.15099583]
 [-0.09065785  0.20462378]
 [-0.23364494  0.10169727]]


### 2. Verify using SVD


In [62]:
U, S, Vt = np.linalg.svd(data - np.mean(data, axis=0), full_matrices=False)
SVD_transformed = np.dot(U[:, :2], np.diag(S[:2]))
print("SVD Transformed Data:\n", SVD_transformed)

SVD Transformed Data:
 [[-0.16903988  0.38660349]
 [-0.23288686 -0.07016475]
 [-0.52227245 -0.1015772 ]
 [ 0.28854069  0.29908826]
 [ 0.33312492 -0.01136668]
 [ 0.05251928 -0.48328433]
 [ 0.51049669  0.13602644]
 [-0.58478517  0.15099583]
 [ 0.09065785 -0.20462378]
 [ 0.23364494 -0.10169727]]


### Practice Problems:

#### Apply PCA to reduce a 5x5 matrix to 2 dimensions.

In [63]:
from sklearn.decomposition import PCA
data = np.random.rand(5, 5)
pca = PCA(n_components=2)
transformed_data = pca.fit_transform(data)
print(transformed_data)

[[-0.50896091  0.22527563]
 [ 0.27068937  0.46643099]
 [ 0.76067116 -0.11997586]
 [-0.04943641 -0.45037731]
 [-0.4729632  -0.12135345]]


#### Perform PCA on a dataset with 50 samples and 10 features.

In [64]:
data = np.random.rand(50, 10)
pca = PCA(n_components=2)
transformed_data = pca.fit_transform(data)
print(transformed_data)

[[ 0.04022695 -0.29168908]
 [-0.58145371 -0.48094805]
 [ 0.54074709  0.1393404 ]
 [-0.37731397  0.14782047]
 [-0.01718075 -0.29688808]
 [ 0.44004326 -0.55919359]
 [ 0.80876209  0.19119802]
 [-0.05812033 -0.09567211]
 [-0.59474206  0.14520157]
 [ 0.82504758  0.21358213]
 [ 0.32280211 -0.37571921]
 [ 0.31780817 -0.69019812]
 [ 0.40958344 -0.2845807 ]
 [ 0.36309089 -0.35284864]
 [ 0.41997212  0.17915534]
 [-0.74032553  0.30514068]
 [-0.27023224  0.28754188]
 [-0.12992883  0.5690381 ]
 [ 0.23779568  0.15863594]
 [-0.55089745 -0.45460331]
 [-0.08741333 -0.3183214 ]
 [ 0.03101224  0.12327557]
 [ 0.04840724 -0.27163021]
 [-0.19180594 -0.33697709]
 [ 0.4338226  -0.34721556]
 [-0.10921538  0.01182782]
 [-0.39822982  0.52422478]
 [-0.16830705  0.14781557]
 [-0.19083625 -0.39257837]
 [-0.46653174  0.42392025]
 [-0.66727533 -0.42457487]
 [ 0.0696097  -0.22025846]
 [ 0.29390292 -0.21865553]
 [-0.58964208  0.12483335]
 [-0.07545757 -0.61189556]
 [ 0.02424143  0.13262795]
 [ 0.40361342  0.47017261]
 

#### Verify PCA results using SVD for a 3x3 matrix.

In [65]:
data = np.random.rand(3, 3)
pca = PCA(n_components=2)
pca_transformed = pca.fit_transform(data)
U, S, Vt = np.linalg.svd(data - np.mean(data, axis=0), full_matrices=False)
SVD_transformed = np.dot(U[:, :2], np.diag(S[:2]))
print("PCA Transformed:\n", pca_transformed)
print("SVD Transformed:\n", SVD_transformed)

PCA Transformed:
 [[-0.4500133  -0.18138628]
 [ 0.51559552 -0.1199814 ]
 [-0.06558223  0.30136768]]
SVD Transformed:
 [[-0.4500133  -0.18138628]
 [ 0.51559552 -0.1199814 ]
 [-0.06558223  0.30136768]]


#### Use PCA to reduce a 20x4 dataset to 3 dimensions.

In [66]:
data = np.random.rand(20, 4)
pca = PCA(n_components=3)
transformed_data = pca.fit_transform(data)
print(transformed_data)

[[-0.0404417   0.25382376  0.34694718]
 [-0.41389531 -0.41700773 -0.31641901]
 [-0.02235466 -0.09318777 -0.05900755]
 [-0.30894577 -0.04527538  0.06426898]
 [-0.21544323 -0.18276719 -0.23529391]
 [ 0.3324777  -0.24627771 -0.35270184]
 [ 0.3928357  -0.35694787  0.51838654]
 [ 0.25594579 -0.01170353 -0.2274103 ]
 [ 0.24520238 -0.3808384   0.12754307]
 [-0.14487409  0.42122653 -0.15030572]
 [-0.4105091  -0.18198243  0.33295899]
 [ 0.12017187 -0.08003832  0.06341057]
 [ 0.40309724  0.09370061  0.07468291]
 [-0.38818857  0.11900347  0.26090644]
 [-0.3848827  -0.13598741 -0.18316057]
 [ 0.39680465  0.33842319 -0.05188595]
 [ 0.58549194  0.03749003 -0.11820273]
 [ 0.07009708  0.13617109 -0.05757075]
 [-0.4326215   0.21340321  0.02093225]
 [-0.03996772  0.51877188 -0.05807861]]


#### Compare PCA and SVD results for a 10x10 matrix.

In [67]:
data = np.random.rand(10, 10)
pca = PCA(n_components=3)
pca_transformed = pca.fit_transform(data)
U, S, Vt = np.linalg.svd(data - np.mean(data, axis=0), full_matrices=False)
SVD_transformed = np.dot(U[:, :3], np.diag(S[:3]))
print("PCA Transformed:\n", pca_transformed)
print("SVD Transformed:\n", SVD_transformed)

PCA Transformed:
 [[ 0.18660619 -0.37090733  0.46576394]
 [-0.6512785  -0.70576499 -0.46283885]
 [-0.97418182 -0.40448515 -0.02081481]
 [ 0.70512769  0.16548449 -0.35934621]
 [-0.85622624  0.47638751  0.37766272]
 [-0.12222244  0.72051919 -0.02119901]
 [-0.17314579  0.55649952  0.00605035]
 [ 0.27387394  0.13639437 -0.46260492]
 [ 1.0798054  -0.0747511   0.07206992]
 [ 0.53164157 -0.4993765   0.40525688]]
SVD Transformed:
 [[-0.18660619  0.37090733  0.46576394]
 [ 0.6512785   0.70576499 -0.46283885]
 [ 0.97418182  0.40448515 -0.02081481]
 [-0.70512769 -0.16548449 -0.35934621]
 [ 0.85622624 -0.47638751  0.37766272]
 [ 0.12222244 -0.72051919 -0.02119901]
 [ 0.17314579 -0.55649952  0.00605035]
 [-0.27387394 -0.13639437 -0.46260492]
 [-1.0798054   0.0747511   0.07206992]
 [-0.53164157  0.4993765   0.40525688]]


# Calculus Tasks
## Numerical Differentiation
### Use NumPy to compute the numerical derivative of a given function:

### 1. Forward Difference

In [68]:
def f(x):
    return x**2 + 3*x + 5

x = np.linspace(0, 10, 100)
h = 1e-5

forward_diff = (f(x + h) - f(x)) / h
forward_diff

array([ 3.00001   ,  3.2020302 ,  3.4040504 ,  3.60607061,  3.80809081,
        4.01011101,  4.21213121,  4.41415141,  4.61617162,  4.81819182,
        5.02021202,  5.22223222,  5.42425242,  5.62627263,  5.82829283,
        6.03031303,  6.23233323,  6.43435343,  6.63637364,  6.83839384,
        7.04041404,  7.24243424,  7.44445444,  7.64647465,  7.84849485,
        8.05051505,  8.25253525,  8.45455545,  8.65657566,  8.85859586,
        9.06061606,  9.26263626,  9.46465646,  9.66667667,  9.86869687,
       10.07071707, 10.27273727, 10.47475747, 10.67677768, 10.87879788,
       11.08081808, 11.28283828, 11.48485848, 11.68687869, 11.88889889,
       12.09091909, 12.29293929, 12.49495949, 12.6969797 , 12.8989999 ,
       13.1010201 , 13.3030403 , 13.50506051, 13.70708071, 13.90910091,
       14.11112111, 14.31314131, 14.51516151, 14.71718172, 14.91920192,
       15.12122212, 15.32324232, 15.52526252, 15.72728273, 15.92930293,
       16.13132313, 16.33334333, 16.53536354, 16.73738374, 16.93

### 2. Backward Difference

In [69]:
backward_diff = (f(x) - f(x - h)) / h
backward_diff

array([ 2.99999   ,  3.2020102 ,  3.4040304 ,  3.60605061,  3.80807081,
        4.01009101,  4.21211121,  4.41413141,  4.61615162,  4.81817182,
        5.02019202,  5.22221222,  5.42423242,  5.62625263,  5.82827283,
        6.03029303,  6.23231323,  6.43433343,  6.63635364,  6.83837384,
        7.04039404,  7.24241424,  7.44443444,  7.64645465,  7.84847485,
        8.05049505,  8.25251525,  8.45453545,  8.65655566,  8.85857586,
        9.06059606,  9.26261626,  9.46463646,  9.66665667,  9.86867687,
       10.07069707, 10.27271727, 10.47473747, 10.67675768, 10.87877788,
       11.08079808, 11.28281828, 11.48483848, 11.68685869, 11.88887889,
       12.09089909, 12.29291929, 12.49493949, 12.6969597 , 12.8989799 ,
       13.1010001 , 13.3030203 , 13.5050405 , 13.70706071, 13.90908091,
       14.11110111, 14.31312131, 14.51514151, 14.71716172, 14.91918192,
       15.12120212, 15.32322232, 15.52524252, 15.72726273, 15.92928293,
       16.13130313, 16.33332333, 16.53534353, 16.73736374, 16.93

### 3. Central Difference


In [70]:
central_diff = (f(x + h) - f(x - h)) / (2 * h)
central_diff

array([ 3.        ,  3.2020202 ,  3.4040404 ,  3.60606061,  3.80808081,
        4.01010101,  4.21212121,  4.41414141,  4.61616162,  4.81818182,
        5.02020202,  5.22222222,  5.42424242,  5.62626263,  5.82828283,
        6.03030303,  6.23232323,  6.43434343,  6.63636364,  6.83838384,
        7.04040404,  7.24242424,  7.44444444,  7.64646465,  7.84848485,
        8.05050505,  8.25252525,  8.45454545,  8.65656566,  8.85858586,
        9.06060606,  9.26262626,  9.46464646,  9.66666667,  9.86868687,
       10.07070707, 10.27272727, 10.47474747, 10.67676768, 10.87878788,
       11.08080808, 11.28282828, 11.48484848, 11.68686869, 11.88888889,
       12.09090909, 12.29292929, 12.49494949, 12.6969697 , 12.8989899 ,
       13.1010101 , 13.3030303 , 13.5050505 , 13.70707071, 13.90909091,
       14.11111111, 14.31313131, 14.51515151, 14.71717172, 14.91919192,
       15.12121212, 15.32323232, 15.52525252, 15.72727273, 15.92929293,
       16.13131313, 16.33333333, 16.53535354, 16.73737374, 16.93

### Practice Problems:

#### Compute the forward difference derivative for  f(x)=x^3 at x=2

In [71]:
h = 1e-5
x = 2
forward_diff = ((x + h)**3 - x**3) / h
print(forward_diff)

12.000060000261213


#### Compute the backward difference derivative for f(x)=sin(x) at x=π/4.

In [72]:
h = 1e-5
x = np.pi / 4
backward_diff = (np.sin(x) - np.sin(x - h)) / h
print(backward_diff)

0.7071103167111125


#### Compute the central difference derivative for f(x)=e^x at x=1.

In [73]:
h = 1e-5
x = 1
central_diff = (np.exp(x + h) - np.exp(x - h)) / (2 * h)
print(central_diff)

2.718281828517632


#### Calculate the numerical derivative for f(x)=ln(x) using the forward difference method at x=2.

In [74]:
h = 1e-5
x = 2
forward_diff = (np.log(x + h) - np.log(x)) / h
print(forward_diff)

0.49999875001427435


#### Calculate the numerical derivative for f(x)=cos(x) using the central difference method at x=0.

In [75]:
h = 1e-5
x = 0
central_diff = (np.cos(x + h) - np.cos(x - h)) / (2 * h)
print(central_diff)

0.0


## Numerical Integration

### Trapezoidal Rule
The trapezoidal rule estimates the integral by approximating the region under the curve as a series of trapezoids.

In [76]:
def f(x):
    return np.sin(x)

a = 0  # Lower limit
b = np.pi  # Upper limit
n = 100  # Number of subintervals
h = (b - a) / n

x = np.linspace(a, b, n + 1)
y = f(x)
integral = (y[0] + y[n]) / 2  # First and last terms
for i in range(1, n):
    integral += y[i]
integral *= h
print(f"The integral of sin(x) from {a} to {b} is approximately: {integral}")

The integral of sin(x) from 0 to 3.141592653589793 is approximately: 1.9998355038874436


### Simpson's Rule
Simpson's rule approximates the integral by fitting parabolas through the data points.

In [77]:
#function to integrate
def f(x):
    return np.sin(x)

a = 0  # Lower limit
b = np.pi  # Upper limit
n = 100  # Number of subintervals (must be even)
if n % 2 != 0:
    raise ValueError("Number of subintervals n must be even.")

h = (b - a) / n
x = np.linspace(a, b, n + 1)
y = f(x)

integral = y[0] + y[n]  # First and last terms
for i in range(1, n, 2):  # Odd indices
    integral += 4 * y[i]
for i in range(2, n - 1, 2):  # Even indices
    integral += 2 * y[i]
integral *= h / 3
print(f"The integral of sin(x) from {a} to {b} is approximately: {integral}")

The integral of sin(x) from 0 to 3.141592653589793 is approximately: 2.0000000108245044


### Practice Problems:

#### Compute the numerical integral of f(x)=x^2 from 0 to 2 using the trapezoidal rule.

In [78]:
def f(x):
    return x**2

a = 0
b = 2
n = 100

h = (b - a) / n
x = np.linspace(a, b, n + 1)
y = f(x)

integral = (y[0] + y[n]) / 2
for i in range(1, n):
    integral += y[i]

integral *= h

print(f"The integral of x^2 from {a} to {b} is approximately: {integral}")

The integral of x^2 from 0 to 2 is approximately: 2.6668000000000003


#### Compute the numerical integral of f(x)=sin(x) from 0 to π using Simpson's rule.

In [79]:
def f(x):
    return np.sin(x)

a = 0
b = np.pi
n = 100

if n % 2 != 0:
    raise ValueError("Number of subintervals n must be even.")

h = (b - a) / n
x = np.linspace(a, b, n + 1)
y = f(x)

integral = y[0] + y[n]
for i in range(1, n, 2):
    integral += 4 * y[i]
for i in range(2, n - 1, 2):
    integral += 2 * y[i]

integral *= h / 3

print(f"The integral of sin(x) from {a} to {b} is approximately: {integral}")

The integral of sin(x) from 0 to 3.141592653589793 is approximately: 2.0000000108245044


#### Calculate the integral of f(x)=e^x from 1 to 3 using the trapezoidal rule.

In [80]:
def f(x):
    return np.exp(x)

a = 1
b = 3
n = 100

h = (b - a) / n
x = np.linspace(a, b, n + 1)
y = f(x)

integral = (y[0] + y[n]) / 2
for i in range(1, n):
    integral += y[i]

integral *= h

print(f"The integral of e^x from {a} to {b} is approximately: {integral}")

The integral of e^x from 1 to 3 is approximately: 17.367833999372426


#### Calculate the integral of f(x)=ln(x) from 1 to 2 using Simpson's rule.

In [81]:
def f(x):
    return np.log(x)

a = 1
b = 2
n = 100

if n % 2 != 0:
    raise ValueError("Number of subintervals n must be even.")

h = (b - a) / n
x = np.linspace(a, b, n + 1)
y = f(x)

integral = y[0] + y[n]
for i in range(1, n, 2):
    integral += 4 * y[i]
for i in range(2, n - 1, 2):
    integral += 2 * y[i]

integral *= h / 3

print(f"The integral of ln(x) from {a} to {b} is approximately: {integral}")

The integral of ln(x) from 1 to 2 is approximately: 0.38629436102268383


#### Compute the numerical integral of f(x)=cos(x) from 0 to π/2 using the trapezoidal rule.

In [82]:
def f(x):
    return np.cos(x)
a, b = 0, np.pi / 2
x = np.linspace(a, b, 1000)
y = f(x)
integral = np.trapz(y, x)
print(integral)

0.999999793971382


## Partial Derivatives
Partial derivatives involve differentiating a multivariable function with respect to one variable, holding the other variables constant.

f(x,y)=x^2 +y^2 at (x,y)=(1,2).

In [83]:
def f(x, y):
    return x**2 + y**2

x, y = 1, 2
h = 1e-5
df_dx = (f(x + h, y) - f(x, y)) / h
df_dy = (f(x, y + h) - f(x, y)) / h
print(df_dx, df_dy)

2.00001000001393 4.000010000027032


#### Calculate the partial derivatives of f(x,y)=x^2+y^2 at (x,y)=(1,2).

In [84]:
def f(x, y):
    return x**2 + y**2
x, y = 1, 2
h = 1e-5
df_dx = (f(x + h, y) - f(x, y)) / h
df_dy = (f(x, y + h) - f(x, y)) / h
print(df_dx, df_dy)

2.00001000001393 4.000010000027032


#### Compute the partial derivatives of f(x,y)=sin(x)cos(y) at (x,y)=(π/4,π/4).

In [85]:
def f(x, y):
    return np.sin(x) * np.cos(y)
x, y = np.pi / 4, np.pi / 4
h = 1e-5
df_dx = (f(x + h, y) - f(x, y)) / h
df_dy = (f(x, y + h) - f(x, y)) / h
print(df_dx, df_dy)

0.49999749998086424 -0.5000024999979313


#### Calculate the partial derivatives of f(x,y)=e^x+y at (x,y)=(0,0).

In [86]:
def f(x, y):
    return np.exp(x + y)
x, y = 0, 0
h = 1e-5
df_dx = (f(x + h, y) - f(x, y)) / h
df_dy = (f(x, y + h) - f(x, y)) / h
print(df_dx, df_dy)

1.000005000006965 1.000005000006965


## Optimization
Optimization involves finding the minimum or maximum of a function. Using scipy.optimize.minimize, we can solve optimization problems with constraints.

f(x)=x^2+3x+2.

In [87]:
from scipy.optimize import minimize

def f(x):
    return x**2 + 3*x + 2

result = minimize(f, 0)
print(result.x)

[-1.50000001]


### Practice Problems:

#### Find the minimum of f(x)=x^2+3x+2.

In [88]:
from scipy.optimize import minimize
def f(x):
    return x**2 + 3*x + 2
result = minimize(f, 0)
print(result.x)

[-1.50000001]


#### Minimize f(x,y)=(x−1)^ 2+ (y−2)^2 with initial guess (0, 0).

In [89]:
def f(x):
    return (x[0] - 1)**2 + (x[1] - 2)**2
result = minimize(f, [0, 0])
print(result.x)

[0.99999999 1.99999999]


#### Find the minimum of f(x)=sin(x)+cos(x) within the interval [0, 2π].

In [90]:
def f(x):
    return np.sin(x) + np.cos(x)
result = minimize(f, np.pi, bounds=[(0, 2*np.pi)])
print(result.x)

[3.92699082]
