# Task 10: Introduction to NumPy (arrays, basic operations)

## Numpy Practice

### importing numpy library

In [1]:
import numpy as np   # we can also write any word of our choice instead of 'np' but 'np' is most commonly used as a standard.

## 1D Array

### 1D array using np.arange

In [2]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1D array using np.array

In [3]:
a2=np.array([1,2,3,4,5,6,7,8,9])
print(a2)

[1 2 3 4 5 6 7 8 9]


In [4]:
type(a2)

numpy.ndarray

### 1D array using np.zeros containing zeros

In [5]:
a4=np.zeros(5)
print(a4)

[0. 0. 0. 0. 0.]


### 1D array using np.ones containing ones

In [6]:
a5=np.ones(10)
print(a5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 1D array using np.random.randint containing random numbers with size and range(min,max) of array specified

In [7]:
a6=np.random.randint(1,10,size=7)
print(a6)

[2 3 1 1 9 8 7]


### 1D array using np.random.rand containing random floats in the range [0, 1) with size of array specified

In [8]:
a7=np.random.rand(7)
print(a7)

[0.35640494 0.40454777 0.38524354 0.71897527 0.06146506 0.56654317
 0.50806506]


### 1D array using np.linspace

In [9]:
a8=np.linspace(0,1,5)  # Creates an array with 5 equally spaced values from 0 to 1
print(a8)

[0.   0.25 0.5  0.75 1.  ]


### Sum of 1D arrays

In [10]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
sum = np.add(array1, array2)
print(sum)

[ 7  9 11 13 15]


### Product of 1D arrays

In [11]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
prod = np.multiply(array1, array2)
print(prod)

[ 6 14 24 36 50]


### Dot Product of 1D arrays

In [12]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
dot_prod = np.dot(array1, array2)
print(dot_prod)

130


### Mean, Median, Mode of 1D arrays

In [13]:
array3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Mean=",np.mean(array3))
print("\nMedian=",np.median(array3))
print("\nMode=",np.std(array3))

Mean= 5.5

Median= 5.5

Mode= 2.8722813232690143


### Min, Max, Cumulative Sum of 1D arrays, Uniform Distribution, Correlation Coefficient Matrix

In [14]:
array4 = np.random.randint(1, 100, size=5)
print(array4)
print("Min=",np.min(array4))
print("\nMax=",np.max(array4))
#uniform_distribution_array = np.random.randint(10, 51, size=(5, 5))
#print("\nCreate a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50 =\n",np.max(array4))
print("\nCumulative Sum =",np.cumsum(array4))
print("\nUniform Distribution=",np.max(array4))
print("\nCorrelation Coefficient Matrix=",np.corrcoef(array4))

[45 10 55 57 40]
Min= 10

Max= 57

Cumulative Sum = [ 45  55 110 167 207]

Uniform Distribution= 57

Correlation Coefficient Matrix= 1.0


### Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1

In [15]:
normal_distribution = np.random.normal(0, 1, 1000)
print(normal_distribution)

[ 1.19325529e+00 -2.40002423e+00 -5.87696097e-01  8.19699415e-01
 -1.20659519e+00 -5.60204199e-01  1.63612729e+00  1.65710819e-02
 -2.14328636e+00  4.09511640e-02  1.34211683e+00  3.96258981e-02
  2.72933153e-01  9.73474753e-01  2.17612853e+00 -1.02449245e+00
  8.80825352e-01  5.80155270e-01  4.57000945e-02  2.17878379e-01
 -3.43930354e-01 -9.78906127e-02  5.18703416e-01  5.86664732e-01
 -1.36055302e+00 -8.95506299e-01  1.57763004e+00 -2.16336032e-01
 -6.24588124e-02  2.29110550e+00  4.48748026e-01 -3.25915237e-01
 -4.99517050e-01  1.09502631e+00  1.23586835e-01  1.23614284e+00
  6.54255491e-01 -1.64118666e+00 -4.54995509e-01  1.65093353e-01
 -9.40888281e-01  8.84445433e-01 -9.36550970e-01 -8.10285518e-02
 -8.21014144e-01  5.71728723e-01  1.60143519e-01 -9.20832063e-01
  1.59189143e+00 -6.34507036e-02  1.41948101e+00  6.04542275e-02
 -1.39542835e-01  8.50314546e-01  1.44952829e+00  2.60932620e-01
 -3.01856045e-01 -2.18252987e+00 -1.09506223e+00 -6.09207558e-02
 -8.97057297e-01 -1.00168

## 2D arrays

### 2D array using np.array

In [16]:
a9=np.array([ [ [1,2],
                [3,4] ],
             
              [ [5,6],
                [7,8] ] ])
print(a9)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 2D array using npa.zeros containing zeros

In [17]:
a10 =np.zeros((3,3))
print(a10)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 2D array using np.ones containing ones

In [18]:
a11 =np.ones((3,3))
print(a11)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 2D array using np.random.randint containing random numbers with size and range(min,max) of array specified

In [19]:
a12 =np.random.randint(1,10,size=(3,3))
print(a12)

[[9 4 8]
 [1 6 4]
 [3 5 5]]


### 2D array using np.random.rand containing random numbers with size of array

In [20]:
a13 =np.random.rand(3,3)
print(a13)

[[0.11551992 0.38531531 0.50297327]
 [0.09853898 0.09562663 0.50520434]
 [0.98340842 0.41412813 0.17994943]]


### 2D array using np.eye creating identity matrix

In [21]:
a14 =np.eye(3)
print(a14)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2D array using np.full /fill 2D array with specified number

In [22]:
a15 =np.full((3,3),7)
print(a15)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Sum, Product, Dot Product of 2D arrays

In [23]:
array1 = np.array([[[1,2],
                    [3,4]],
             
                  [[5,6],
                    [7,8]]])
array2 = np.array([[[4,2],
                    [11,9]],
             
                  [[11,20],
                    [100,50]]])
sum = np.add(array1, array2)
print("\nSum:",sum)
prod = np.multiply(array1, array2)
print("\nProduct=",prod)
dot_prod = np.dot(array1, array2)
print("\nDot Product=",dot_prod)


Sum: [[[  5   4]
  [ 14  13]]

 [[ 16  26]
  [107  58]]]

Product= [[[  4   4]
  [ 33  36]]

 [[ 55 120]
  [700 400]]]

Dot Product= [[[[ 26  20]
   [211 120]]

  [[ 56  42]
   [433 260]]]


 [[[ 86  64]
   [655 400]]

  [[116  86]
   [877 540]]]]


### Mean, Median, Mode of 2D arrays

In [24]:
array3 = np.random.randint(1,10,size=(3,3))
print("Mean=",np.mean(array3))
print("\nMedian=",np.median(array3))
print("\nMode=",np.std(array3))

Mean= 6.0

Median= 7.0

Mode= 3.018461712712472


### Min, Max, Cumulative Sum of 2D arrays, Uniform Distribution, Correlation Coefficient Matrix

In [25]:
array4 = np.random.randint(1, 100, size=(4, 5))
print(array4)
print("Min=",np.min(array4))
print("\nMax=",np.max(array4))
uniform_distribution_array = np.random.randint(10, 51, size=(5, 5))
print("\nCreate a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50 =\n",uniform_distribution_array)
print("\nCumulative Sum =",np.cumsum(array4))
print("\nCorrelation Coefficient Matrix=",np.corrcoef(array4))

[[41 76 56 69 32]
 [18 16 42 61 22]
 [73 59 63 59 33]
 [31 19 21 77 62]]
Min= 16

Max= 77

Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50 =
 [[10 24 29 18 28]
 [21 14 42 14 17]
 [20 26 13 25 39]
 [49 44 38 15 20]
 [37 17 40 19 28]]

Cumulative Sum = [ 41 117 173 242 274 292 308 350 411 433 506 565 628 687 720 751 770 791
 868 930]

Correlation Coefficient Matrix= [[ 1.          0.35461896  0.37028953 -0.1663294 ]
 [ 0.35461896  1.          0.0895871   0.55970375]
 [ 0.37028953  0.0895871   1.         -0.49164391]
 [-0.1663294   0.55970375 -0.49164391  1.        ]]


## 3D arrays

### 3D array using np.array

In [26]:
a16 = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
print(a16)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 3D array using npa.zeros containing zeros

In [27]:
a17 = np.zeros((2, 3, 4)) 
print(a17)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### 3D array using np.ones containing ones

In [28]:
a18 = np.ones((2, 3, 4)) 
print(a18)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### 3D array using np.random.randint containing random numbers with size and range(min,max) of array specified

In [29]:
a19 = np.random.randint(1,20,size=(2, 3, 4)) 
print(a19)

[[[ 2  5 18  6]
  [17 18  5  4]
  [ 3 18  4  5]]

 [[12 16  9  6]
  [ 6  1 16 18]
  [ 8  3  7 13]]]


### 3D array using np.random.rand containing random numbers with size of array

In [30]:
a20 = np.random.rand(3,3,3) 
print(a20)

[[[0.58448608 0.40136979 0.67006537]
  [0.52752932 0.09258085 0.49655591]
  [0.96826142 0.54402012 0.12064615]]

 [[0.04209877 0.67888718 0.70176562]
  [0.26885063 0.89204338 0.30986658]
  [0.05644937 0.37164034 0.43991465]]

 [[0.9725441  0.84822663 0.36252556]
  [0.64763605 0.68916485 0.32168954]
  [0.48926698 0.76716656 0.44848634]]]


### 3D array using np.full 

In [31]:
a21= np.full((2,3,4),7) 
print(a21)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]


### 3D array using np.arange and reshape 

In [32]:
a22 = np.arange(24).reshape((2, 3, 4))  # Creates a 2x3x4 array with values from 0 to 23
print(a22)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### Sum, Product, Dot Product of 3D arrays

In [33]:
array1 = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
array2 = np.array([[[10, 20, 30], [40, 50, 60]],
                [[70, 80, 90], [100, 110, 120]]])
sum = np.add(array1, array2)
print("\nSum:",sum)
prod = np.multiply(array1, array2)
print("\nProduct=",prod)

array3=array1.reshape(3,2,2)
array4=array2.reshape(3,2,2)
dot_prod = np.dot(array3, array3)
print("\nDot Product=",dot_prod)


Sum: [[[ 11  22  33]
  [ 44  55  66]]

 [[ 77  88  99]
  [110 121 132]]]

Product= [[[  10   40   90]
  [ 160  250  360]]

 [[ 490  640  810]
  [1000 1210 1440]]]

Dot Product= [[[[  7  10]
   [ 19  22]
   [ 31  34]]

  [[ 15  22]
   [ 43  50]
   [ 71  78]]]


 [[[ 23  34]
   [ 67  78]
   [111 122]]

  [[ 31  46]
   [ 91 106]
   [151 166]]]


 [[[ 39  58]
   [115 134]
   [191 210]]

  [[ 47  70]
   [139 162]
   [231 254]]]]


### Mean, Median, Mode of 3D arrays

In [34]:
array3 = np.random.randint(1,10,size=(3,3,3))
print("Mean=",np.mean(array3))
print("\nMedian=",np.median(array3))
print("\nMode=",np.std(array3))

Mean= 5.111111111111111

Median= 5.0

Mode= 2.601044424604361


### Min, Max, Cumulative Sum of 3D arrays, Uniform Distribution

In [35]:
array4 = np.random.randint(1, 100, size=(2, 3, 4))
print(array4)
print("Min=",np.min(array4))
print("\nMax=",np.max(array4))
uniform_distribution_array = np.random.randint(10, 51, size=(5, 5, 5))
print("\nCreate a 3D array of shapes (5, 5, 5) with random integers from a uniform distribution between 10 and 50 =\n",uniform_distribution_array)
print("\nCumulative Sum =",np.cumsum(array4))

[[[29 34 84 78]
  [78 95 44 69]
  [42 57 11 48]]

 [[80 14 23 72]
  [89 43 75 96]
  [51 99 89  2]]]
Min= 2

Max= 99

Create a 3D array of shapes (5, 5, 5) with random integers from a uniform distribution between 10 and 50 =
 [[[50 19 36 16 18]
  [25 38 21 20 34]
  [28 29 46 14 33]
  [29 27 23 46 29]
  [28 37 22 27 22]]

 [[30 46 47 30 20]
  [27 49 32 19 43]
  [10 19 13 30 48]
  [30 31 32 22 10]
  [28 20 48 32 11]]

 [[20 19 20 45 19]
  [27 11 48 35 37]
  [27 50 10 36 46]
  [47 12 10 14 21]
  [50 39 32 10 10]]

 [[28 16 18 12 38]
  [22 23 32 21 33]
  [29 33 48 33 49]
  [49 46 27 10 37]
  [11 33 26 38 30]]

 [[45 30 23 11 22]
  [49 28 20 44 36]
  [12 33 37 36 10]
  [48 32 30 14 23]
  [43 26 42 13 39]]]

Cumulative Sum = [  29   63  147  225  303  398  442  511  553  610  621  669  749  763
  786  858  947  990 1065 1161 1212 1311 1400 1402]


## Some Problems of Task 09

### Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.

In [36]:
die_rolls = np.random.randint(1, 7, size=1000)
die_rolls_frequency = np.bincount(die_rolls)[1:]  # bincount includes zero count
print(die_rolls_frequency)

[147 163 193 175 151 171]


### Find the mean of the following set of numbers: 2, 4, 6, 8, 10.

In [37]:
numbers = np.array([2, 4, 6, 8, 10])
mean_numbers = np.mean(numbers)
print(mean_numbers)

6.0


### The daily temperatures for a week are recorded as 20°C, 22°C, 19°C, 24°C, 21°C, 23°C, and 20°C. Calculate the mean temperature

In [38]:
temperatures = np.array([20, 22, 19, 24, 21, 23, 20])
mean_temperature = np.mean(temperatures)
print(mean_temperature)

21.285714285714285


### Find the median of the set: 3, 1, 4, 1, 5, 9.

In [39]:
set1 = np.array([3, 1, 4, 1, 5, 9])
median_set1 = np.median(set1)
print(median_set1)

3.5


### Determine the median of these numbers: 45, 67, 23, 89, 12, 54, 33, 72.

In [40]:
set2 = np.array([45, 67, 23, 89, 12, 54, 33, 72])
median_set2 = np.median(set2)
print(median_set2)

49.5


### Identify the mode in the dataset: 5, 3, 9, 3, 2, 3, 4, 6, 5.

In [41]:
mode_set1 = np.std([5, 3, 9, 3, 2, 3, 4, 6, 5])
print(mode_set1)

2.006163342807532


### Find the mode of the following test scores: 56, 72, 89, 56, 94, 56, 78, 72.

In [42]:
mode_set2 = np.std([56, 72, 89, 56, 94, 56, 78, 72])
print(mode_set2)

14.03511221900274


### Given a normal distribution with a mean of 50 and a standard deviation of 5, find the probability that a value is between 45 and 55.

In [43]:
from scipy import special,stats # used form finding norm and combination and other mathematical function
mean = 50
std_dev = 5
prob_between_45_55 = stats.norm.cdf(55, mean, std_dev) - stats.norm.cdf(45, mean, std_dev)
print(prob_between_45_55)

0.6826894921370859


### Calculate the z-score for a value of 60 in a normal distribution with a mean of 50 and a standard deviation of 10.

In [44]:
value = 60
mean = 50
std_dev = 10
z_score = (value - mean) / std_dev
print(z_score)

1.0


### If a coin is flipped 10 times, what is the probability of getting exactly 6 heads?

In [45]:
n = 10
k = 6
p = 0.5
prob_6_heads = special.comb(n, k) * (p ** k) * ((1 - p) ** (n - k))
print(prob_6_heads)

0.205078125


### In a survey, 60% of people prefer chocolate ice cream. What is the probability that out of 8 randomly selected people, exactly 5 prefer chocolate ice cream?

In [46]:
p_chocolate = 0.6
n_people = 8
k_chocolate = 5
prob_5_chocolate = special.comb(n_people, k_chocolate) * (p_chocolate ** k_chocolate) * ((1 - p_chocolate) ** (n_people - k_chocolate))
print(prob_5_chocolate)

0.27869184


### A call center receives an average of 5 calls per hour. What is the probability of receiving exactly 3 calls in an hour?

In [47]:
lambda_calls = 5
k_calls = 3
prob_3_calls = (lambda_calls ** k_calls * np.exp(-lambda_calls)) / special.factorial(k_calls)
print(prob_3_calls)

0.14037389581428056


### If a book has an average of 2 misprints per page, what is the probability that a page has no misprints?

In [48]:
lambda_misprints = 2
k_misprints = 0
prob_no_misprints = (lambda_misprints ** k_misprints * np.exp(-lambda_misprints)) / special.factorial(k_misprints)
print(prob_no_misprints)

0.1353352832366127
